spring:
  application:
    name: spring-cache-example

server:
  port: 8081

cache:
  token1:
    timeToLiveSeconds: 4
    maxElementEntries: 1
  token2:
    timeToLiveSeconds: 4
    maxElementEntries: 1
