spring:
  application:
    name: spring-cache-example

server:
  port: 8081

cache:
  token1:
    timeToLiveSeconds: 40
    maxElementEntries: 10
  token2:
    timeToLiveSeconds: 10
    maxElementEntries: 5
